create table if not exists public.prayer_intentions (
  id bigint generated by default as identity primary key,
  submitter_name text not null,
  name text not null check (char_length(trim(name)) between 1 and 200),
  intention text not null check (char_length(trim(intention)) between 1 and 5000),
  mass_time text not null,
  created_at timestamptz not null default now()
);

alter table public.prayer_intentions
add column if not exists submitter_name text;

update public.prayer_intentions
set submitter_name = 'Unknown'
where submitter_name is null;

alter table public.prayer_intentions
alter column submitter_name set not null;

alter table public.prayer_intentions
drop constraint if exists prayer_intentions_submitter_name_check;

alter table public.prayer_intentions
add constraint prayer_intentions_submitter_name_check
check (char_length(trim(submitter_name)) between 1 and 200);

alter table public.prayer_intentions enable row level security;

drop policy if exists "Allow anyone to submit prayer intentions"
on public.prayer_intentions;

create policy "Allow anyone to submit prayer intentions"
on public.prayer_intentions
for insert
to anon
with check (true);
